version: 2.1
orbs:
  go: circleci/go@1.7.3

jobs:
  build_and_test: # this can be any name you choose
    executor:
      name: go/default # Use the default executor from the orb
      tag: '1.20.8' # Specify a version tag
    steps:
      - checkout # checkout source code
      - go/load-cache # Load cached Go modules.
      - go/mod-download # Run 'go mod download'.
      - go/save-cache # Save Go modules to cache.
      - run: 
          name: Check Formatting with gofmt
          command: |
            echo "Running gofmt..."
            test -z $(gofmt -l .)
      - run:
          name: Lint with golint
          command: |
            echo "Installing golint..."
            go install golang.org/x/lint/golint@latest
            echo "Running golint..."
            golint -set_exit_status ./...
      - run:
          name: Vet with go vet
          command: |
            echo "Running go vet..."
            go vet ./...
      - go/test: # Runs 'go test ./...' but includes extensive parameterization for finer tuning.
          covermode: atomic
          failfast: true
          race: true
      - persist_to_workspace:
          root: ~/project
          paths: .

workflows:
  test_my_app:
    jobs:
      - build_and_test